module.exports = {
  user: {
    userNotFound: "User not found",
    userFound: "User found",
    listShared: "List of shared users",
    userUpdated: "User updated successfully",
    userValidated: "User validated successfully",
    registered: "User Registered successfully",
    loggedIn: "User logged in successfully",
    passwordReset: "Password reset successfully",
    tempPassword: "Temporary password sent to your email",
    success: "Success",
    delete: "Successfully deleted",
    refreshToken: "token generated successfully",
  },
  product: {
    productNotFound: "Product not found",
    productFound: "Products found",
    productCreated: "Product created successfully",
    productUpdated: "Product updated successfully",
    productDeleted: "Product deleted successfully",
    errorCreatingProduct: "Error creating product",
    errorUpdatingProduct: "Error updating product",
    errorDeletingProduct: "Error deleting product",
    error: "Error",
    stockEmail: "email is sent regarding stock",
  },
  error: {
    errorRegistering: "Error registering user",
    errorLoggingIn: "Error logging in user",
    errorUploading: "Error uploading image",
    errorGettingUser: "Error getting user",
    errorResettingPassword: "Error resetting password",
    passwordNotMatch: "Password does not match",
    invalidToken: "Invalid token",
    tokenEmpty: "No token is provided",
    tokenExpired: "Token expired",
    invalidPassword: "Invalid Password",
    invalidBody: "Invalid body fields",
    unprocessableEntity: "Validation Error",
    internalServerError: "Internal Server Error",
    failed: "Failed",
    emailExists: "Email already exists",
    phoneNumberExists: "Phone number already exists",
    userExists: "User already exists",
    notAuthorized: "You are not authorized to perform this action",
  },

  cart: {
    cartNotFound: "Cart not found",
    cartFound: "Cart found",
    cartCreated: "Cart created successfully",
    cartUpdated: "Cart updated successfully",
    cartDeleted: "Cart deleted successfully",
    errorCreatingCart: "Error creating cart",
    errorDeleteCart: "Error deleting cart",
    errorUpdatingCart: "Error updating cart",
    errorViewCart: "Error viewing cart",
  },

  category: {
    categoryNotFound: "Category not found",
    categoryFound: "Category found",
    categoryCreated: "Category created successfully",
    categoryUpdated: "Category updated successfully",
    categoryDeleted: "Category deleted successfully",
    errorCreatingCategory: "Error creating category",
    errorUpdatingCategory: "Error updating category",
    errorDeletingCategory: "Error deleting category",
    errorViewingCategory: "Error viewing category",
  },
  unit: {
    unitNotFound: "Unit not found",
    unitFound: "Unit found",
    unitCreated: "Unit created successfully",
    unitUpdated: "Unit updated successfully",
    unitDeleted: "Unit deleted successfully",
    errorCreatingUnit: "Error creating unit",
    errorUpdatingUnit: "Error updating unit",
    errorDeletingUnit: "Error deleting unit",
    errorViewingUnit: "Error viewing unit",
  },

  sales: {
    salesNotFound: "Sales not found",
    salesFound: "Sales found",
    salesCreated: "Sales created successfully",
    salesUpdated: "Sales updated successfully",
    salesDeleted: "Sales deleted successfully",
    errorCreatingSales: "Error creating sales",
    errorUpdatingSales: "Error updating sales",
    errorDeletingSales: "Error deleting sales",
    errorViewingSales: "Error viewing sales",
  },
  order: {
    orderNotFound: "Order not found",
    orderFound: "Order found",
    orderCreated: "Order created successfully",
    orderUpdated: "Order updated successfully",
    orderDeleted: "Order deleted successfully",
    errorCreatingOrder: "Error creating order",
    errorUpdatingOrder: "Error updating order",
    errorDeletingOrder: "Error deleting order",
    errorViewingOrder: "Error viewing order",
  },
};
